version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: |
            make bootstrap
      - run:
          name: Fetch Carthage dependencies
          command: |
            make carthage-fetch
      - run:
          name: Setup Project
          command: |
            make setup-project
      - run:
          name: Build and run tests
          command: |
            make build-app
            make test-core
            make test-ui
            make test-testing
            make test-search
            make test-home
            make test-app